apiVersion: batch/v1
kind: Job
metadata:
  name: pe-wa-job
spec:
  template:
    spec:
      containers:
      - name: pe-wa-job
        image: yash5090/pe-wa:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
