apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-santa-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: secret-santa
  template:
    metadata:
      labels:
        app: secret-santa
    spec:
      containers:
        - name: secret-santa
          image: yash5090/secret-santa:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
